name: Build JavaDocs

on:
  workflow_dispatch:
  push:
    branches:
      - avdivan-patch-1
  pull_request:
    branches:
      - avdivan-patch-1

jobs:
  build-javadoc:
    name: Build JavaDocs ${{ matrix.branch }}
    runs-on: ubuntu-22.04
    container:
      image: quay.io/opencv-ci/opencv-androidsdk-34:20250516
      options: --user ci
    strategy:
      matrix:
        branch: [4.x, 5.x]
    env:
      OPENCV_DIR: /home/ci/opencv
      JAVA_SRC: /home/ci/opencv/modules/java/generator/src/java
      JDK_HOME: /usr/lib/jvm/java-11-openjdk-amd64  # может быть другим, проверим
    steps:
      - name: Checkout OpenCV
        run: |
          git clone --branch ${{ matrix.branch }} https://github.com/opencv/opencv.git $OPENCV_DIR

      - name: Build JavaDocs
        run: |
          mkdir -p /home/ci/javadoc
          javadoc \
            -d /home/ci/javadoc \
            -sourcepath $JAVA_SRC \
            -subpackages org.opencv \
            -Xdoclint:none

      - name: Archive Javadoc
        uses: actions/upload-artifact@v4
        with:
          name: opencv-javadoc-${{ matrix.branch }}
          path: /home/ci/javadoc
