name: Build OpenCV JavaDocs

on:
  workflow_dispatch:
  push:
    branches:
      - avdivan-patch-1
  pull_request:
    branches:
      - avdivan-patch-1

jobs:
  build-javadoc:
    name: JavaDocs ${{ matrix.branch }}
    runs-on: ubuntu-22.04
    container:
      image: quay.io/ivan_avdeev/opencv_test:opencv-docs-22.04-jdk-20250526
      options: --user ci
    strategy:
      matrix:
        branch: [4.x, 5.x]
    env:
      OPENCV_SRC: /home/ci/opencv
      OPENCV_BUILD: /home/ci/opencv-build
      JAVA_OUT: /home/ci/opencv-build/java
      JAVA_DOC: /home/ci/javadoc
    steps:
      - name: Checkout OpenCV
        run: |
          git clone --branch ${{ matrix.branch }} https://github.com/opencv/opencv.git $OPENCV_SRC
          
          
      - name: Configure CMake (generate Java sources)
        run: |
          mkdir -p $OPENCV_BUILD
          cd $OPENCV_BUILD
          cmake -DBUILD_SHARED_LIBS=OFF \
                -DBUILD_opencv_java=ON \
                -DCMAKE_BUILD_TYPE=Release \
                -DANT_EXECUTABLE=/usr/bin/ant \
                $OPENCV_SRC

      - name: Build Java bindings
        run: |
          cd $OPENCV_BUILD
          cmake --build . --target opencv_java -- -j2

      - name: Generate Javadoc
        run: |
          mkdir -p $JAVA_DOC
          find $JAVA_OUT -name "*.java" > sources.txt
          javadoc -d $JAVA_DOC @sources.txt -Xdoclint:none

      - name: Archive Javadoc
        uses: actions/upload-artifact@v4
        with:
          name: opencv-javadoc-${{ matrix.branch }}
          path: $JAVA_DOC
