name: OCV PR Windows

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/OCV-PR-Windows.yaml'
      # TODO: are following paths necessary?
      - 'checkout-and-merge/*'
      - 'configure-and-build/*'
      - 'run-tests/*'
      - 'scripts/runner.py'
      - 'scripts/test-plan.json'
  workflow_call:
    inputs:
      workflow_branch:
        description: "Branch for ci-gha-workflow repository"
        default: "main"
        required: false
        type: string

concurrency:
  group: OCV-PR-Windows-${{ github.ref }}
  cancel-in-progress: true

jobs:

  branch_eval:
    runs-on: ubuntu-24.04
    outputs:
      branches: ${{ steps.determine-branches.outputs.branches }}
    steps:
        - id: determine-branches
          shell: bash
          run: |
            if [ "${{ github.event.repository.name == 'ci-gha-workflow' }}" = "true" ] ; then
              echo "branches=[ '4.x', '5.x' ]" >> "$GITHUB_OUTPUT"
            else
              echo "branches=[ '${{ github.base_ref }}' ]" >> "$GITHUB_OUTPUT"
            fi

  Windows:
    runs-on: opencv-cn-win
    needs:
      - branch_eval
    strategy:
      # NOTE: Debugging
      fail-fast: true
      # fail-fast: false
      max-parallel: 3
      matrix:
        config:
          - 'base'
          - 'vulkan'
          - 'uwp'

        branch: ${{ fromJSON(needs.branch_eval.outputs.branches )}}

    defaults:
      run:
        shell: bash
    env:
      OPENCV_DOWNLOAD_PATH: "${{ env.BINARIES_CACHE }}"
      CMAKE_OPT: >-
        -DCL_Z_OPTION=/Z7
        -DBUILD_EXAMPLES=ON
        -DOPENCV_ENABLE_NONFREE=ON
      MAIN_BUILD_DIR: "${{ (github.event.repository.name != 'opencv_contrib') && 'build' || 'build-contrib' }}"
      OPENCV_FOR_THREADS_NUM: 8
      CMAKE_BUILD_PARALLEL_LEVEL: 8

    # ==========

    steps:

    - name: Checkout workflow repository
      uses: actions/checkout@v4
      with:
        repository: opencv/ci-gha-workflow
        ref: "${{ github.repository == 'opencv/ci-gha-workflow' && github.ref || inputs.workflow_branch }}"

    - name: Checkout and merge OpenCV
      uses: ./checkout-and-merge
      with:
        target_branch: "${{ matrix.branch }}"
        author: "${{ github.event.pull_request.user.login }}"
        source_branch: "${{ github.event.repository.name == 'ci-gha-workflow' && '' || github.head_ref }}"
        gitcache: "${{ env.GIT_CACHE }}"
        workdir: "${{ github.workspace }}"
