name: "OCV PR Windows ARM"

on:
  pull_request:
    branches: [ main-warm ]
  push:
    branches: [ main-warm ]
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner label (windows-11-arm for public repos)"
        required: true
        default: "windows-11-arm"
      opencv_branch:
        description: "OpenCV branch to build (e.g. 4.x or 5.x)"
        required: false
        default: "5.x"

jobs:
  branch_eval:
    runs-on: ubuntu-24.04
    outputs:
      branches: ${{ steps.out.outputs.branches }}
    steps:
      - id: out
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ inputs.opencv_branch }}" ]; then
            echo "branches=[ '${{ inputs.opencv_branch }}' ]" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          if [ "${{ github.event.repository.name == 'ci-gha-workflow' }}" = "true" ] ; then
            echo "branches=[ '4.x', '5.x' ]" >> "$GITHUB_OUTPUT"
          else
            echo "branches=[ '${{ github.base_ref || github.ref_name }}' ]" >> "$GITHUB_OUTPUT"
          fi

  Build:
    runs-on: ${{ github.event_name == 'workflow_dispatch' && inputs.runner || 'windows-11-arm' }}
    needs: [branch_eval]
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        branch: ${{ fromJSON(needs.branch_eval.outputs.branches) }}
    defaults:
      run:
        shell: bash
    env:
      CMAKE_OPT: >-
        -DCL_Z_OPTION=/Z7
        -DBUILD_EXAMPLES=ON
        -DOPENCV_ENABLE_NONFREE=ON
        -DWITH_OPENCL=OFF
      MAIN_BUILD_DIR: "build-arm"
      OPENCV_FOR_THREADS_NUM: 8
      CMAKE_BUILD_PARALLEL_LEVEL: 8

    steps:
      - name: Checkout workflow repository
        uses: acti
